#import "animation_asset.h"
#include <bit>
namespace ssx {
namespace {
NSDictionary* json(NSString* path){NSData*d=[NSData dataWithContentsOfFile:path];if(!d)throw std::runtime_error("Missing animation asset JSON");id object=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil];if(![object isKindOfClass:NSDictionary.class])throw std::runtime_error("Invalid animation asset JSON");return object;}
AnimationVector vec(NSArray*a){if(a.count<3)throw std::runtime_error("Invalid source animation position");return {[a[0]floatValue],[a[1]floatValue],[a[2]floatValue]};}
AnimationQuaternion quat(NSArray*a){if(a.count!=4)throw std::runtime_error("Invalid source animation rotation");return {[a[0]floatValue],[a[1]floatValue],[a[2]floatValue],[a[3]floatValue]};}
}
AnimationRigAsset loadOriginalAnimationBindings(NSString* folder){
    AnimationRigAsset result;auto rig=json([folder stringByAppendingPathComponent:@"rider.json"]);
    result.character=[rig[@"character"]UTF8String]?:[folder.lastPathComponent.lowercaseString UTF8String];
    for(NSDictionary*b in rig[@"bones"]){AnimationBone bone;bone.parent=[b[@"parent"]intValue];bone.part=[b[@"file"]intValue];bone.translationChannel=[b[@"animation_translation_channel"]intValue];bone.rotationChannel=[b[@"animation_rotation_channel"]intValue];
        if(b[@"source_translation_cm"]&&b[@"source_rotation"])bone.bind={vec(b[@"source_translation_cm"]),quat(b[@"source_rotation"])};
        else{auto t=vec(b[@"translation"]);auto q=quat(b[@"rotation"]);bone.bind={{t[0]*100,-t[2]*100,t[1]*100},{q[0],-q[2],q[1],q[3]}};}
        if([b[@"source_translation_bits"]count]==4&&[b[@"source_rotation_bits"]count]==4){for(unsigned k=0;k<3;++k)bone.bind.position[k]=std::bit_cast<float>([b[@"source_translation_bits"][k]unsignedIntValue]);for(unsigned k=0;k<4;++k)bone.bind.rotation[k]=std::bit_cast<float>([b[@"source_rotation_bits"][k]unsignedIntValue]);}result.bones.push_back(bone);}
    NSArray*sourceBones=rig[@"bones"];for(unsigned i=0;i<result.bones.size();++i){NSDictionary*b=sourceBones[i];auto&bone=result.bones[i];int mirrorIndex=[b[@"mirror_index"]intValue];for(unsigned j=0;j<result.bones.size();++j)if(result.bones[j].part==bone.part&&[sourceBones[j][@"index"]intValue]==mirrorIndex)bone.mirrorSource=int(j);if(bone.mirrorSource<0)throw std::runtime_error("Missing original mirror bone");NSArray*map=b[@"mirror_quaternion_map"];for(unsigned k=0;k<4;++k)bone.mirrorQuaternion[k]=[map[k]unsignedCharValue];bone.mirrorTranslation=vec(b[@"mirror_translation_scale"]);}
    return result;
}
AnimationRigAsset loadOriginalAnimationRig(NSString* folder){
    AnimationRigAsset result=loadOriginalAnimationBindings(folder);
    auto manifest=json([folder stringByAppendingPathComponent:@"animation-packets.json"]);NSData*data=[NSData dataWithContentsOfFile:[folder stringByAppendingPathComponent:@"animation-packets.bin"]];if(!data)throw std::runtime_error("Missing animation packets");
    for(NSDictionary*c in manifest[@"clips"]){AnimationClip clip;clip.id=[c[@"id"]unsignedIntValue];clip.duration=[c[@"duration"]floatValue];for(NSNumber*t in c[@"event_times"])clip.eventTimes.push_back(t.floatValue);if(clip.eventTimes.size()>63)throw std::runtime_error("Too many authored animation events");for(NSDictionary*p in c[@"packets"]){size_t at=[p[@"offset"]unsignedLongLongValue],size=[p[@"size"]unsignedLongLongValue];if(at>data.length||size>data.length-at)throw std::runtime_error("Animation packet outside asset");clip.segments.push_back({[p[@"part"]intValue],AnimationPacket(std::span(static_cast<const uint8_t*>(data.bytes)+at,size),[p[@"frames"]unsignedIntValue])});}result.clips.push_back(std::move(clip));}
    for(NSString*key in manifest[@"cycle_maps"]){NSArray*ids=manifest[@"cycle_maps"][key];if(ids.count!=5)throw std::runtime_error("Invalid five-way animation map");std::array<uint32_t,5> values;for(unsigned i=0;i<5;++i)values[i]=[ids[i]unsignedIntValue];result.cycleMaps[[key intValue]]=values;}
    for(NSString*key in manifest[@"three_way_maps"]){NSArray*ids=manifest[@"three_way_maps"][key];if(ids.count!=3)throw std::runtime_error("Invalid three-way animation map");std::array<uint32_t,3> values;for(unsigned i=0;i<3;++i)values[i]=[ids[i]unsignedIntValue];result.threeWayMaps[[key intValue]]=values;}
    for(NSString*collection in @[@"state_properties",@"state_definitions"])for(NSDictionary*d in manifest[collection]){AnimationStateDefinition state;state.semantic=[d[@"semantic"]intValue];state.animationClass=[d[@"animation_class"]intValue];state.kind=[d[@"kind"]intValue];state.completionKind=[d[@"completion_kind"]unsignedIntValue];state.channel=[d[@"channel"]intValue];state.blendSeconds=[d[@"blend_seconds"]floatValue];state.firstFadeIn=[d[@"first_fade_in"]floatValue];state.endFadeOut=[d[@"end_fade_out"]floatValue];state.initialClip=d[@"initial_clip"]?[d[@"initial_clip"]unsignedIntValue]:0xffffffffu;state.followupClip=[d[@"followup_clip"]unsignedIntValue];result.stateDefinitions[state.semantic]=state;}
    for(NSString*key in manifest[@"animation_variants"]){NSArray*records=manifest[@"animation_variants"][key];if(records.count==0||records.count>32767)throw std::runtime_error("Invalid original variant range");auto&choices=result.animationVariants[[key intValue]];for(NSDictionary*v in records){OriginalAnimationVariant choice{[v[@"leaf"]unsignedIntValue],[v[@"weight"]unsignedIntValue],[v[@"allowed_flags"]unsignedIntValue]};choices.push_back(choice);if(choice.leaf!=519){if(![v[@"clip"]isKindOfClass:NSNumber.class])throw std::runtime_error("Missing variant clip");uint32_t clip=[v[@"clip"]unsignedIntValue];auto[found,added]=result.variantClips.emplace(choice.leaf,clip);if(!added&&found->second!=clip)throw std::runtime_error("Conflicting original leaf mapping");}}}
    return result;
}
std::vector<AnimationLayer> readOriginalAnimationLayers(NSArray* layers){std::vector<AnimationLayer>result;for(NSDictionary*l in layers){AnimationLayer layer;layer.clip=[l[@"clip"]unsignedIntValue];layer.time=[l[@"time"]floatValue];layer.weight=[l[@"weight"]floatValue];layer.priority=[l[@"priority"]intValue];layer.mask=[l[@"mask"]unsignedLongLongValue];layer.mirror=[l[@"mirror"]boolValue];if(l[@"root_position"])layer.root.position=vec(l[@"root_position"]);if(l[@"root_rotation"])layer.root.rotation=quat(l[@"root_rotation"]);result.push_back(layer);}return result;}
}
