#import "animation_asset.h"
#include "rider_pose_motion.hpp"
#include "air_control.hpp"
#include <cfenv>
#include <cstdio>
#include <bit>
#include <cstring>
int main(int argc,char**argv){@autoreleasepool{try{
    if(argc!=3)throw std::runtime_error("Expected rider folder and comparison JSON");
    auto rig=ssx::loadOriginalAnimationRig(@(argv[1]));NSData*d=[NSData dataWithContentsOfFile:@(argv[2])];NSDictionary*fixture=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil];
    auto layers=ssx::readOriginalAnimationLayers(fixture[@"layers"]);auto local=ssx::originalAnimationLocalPose(rig.bones,rig.clips,layers,fixture[@"bone_mask"]?[fixture[@"bone_mask"]unsignedLongLongValue]:~uint64_t(0));
    auto vec=[](NSArray*a){return ssx::AnimationVector{[a[0]floatValue],[a[1]floatValue],[a[2]floatValue]};};NSArray* q=fixture[@"root_rotation"];
    ssx::AnimationTransform root{vec(fixture[@"root_position_cm"]),{[q[0]floatValue],[q[1]floatValue],[q[2]floatValue],[q[3]floatValue]}};
    if([fixture[@"air_state"]isKindOfClass:NSDictionary.class]){NSDictionary*s=fixture[@"air_state"];ssx::OriginalAirControlState air;air.totalSpin=[s[@"total_spin"]floatValue];air.totalFlip=[s[@"total_flip"]floatValue];air.adjustSpin=[s[@"adjust_spin"]floatValue];air.adjustFlip=[s[@"adjust_flip"]floatValue];air.axisBlend=[s[@"axis_blend"]floatValue];air.spinRate=[s[@"spin_rate"]floatValue];air.flipRate=[s[@"flip_rate"]floatValue];unsigned bone=[fixture[@"pivot_bone"]unsignedIntValue];auto scale=vec(fixture[@"scale"]);int mode=std::fegetround();std::fesetround(FE_TOWARDZERO);ssx::AnimationVector pivot;for(unsigned k=0;k<3;++k)pivot[k]=local.at(bone).position[k]*scale[k];std::fesetround(mode);auto presented=ssx::originalAirPresentationCurrent(air,{root.position,root.rotation},pivot);root={presented.position,presented.quaternion};}
    auto secondaryRoot=root;
    if(NSDictionary*p=fixture[@"presentation"]){ssx::RiderRootPresentation state;state.turn=[p[@"turn"]floatValue];state.extraLean=[p[@"extra_lean"]floatValue];state.brake=[p[@"brake"]floatValue];state.roll=[p[@"roll"]floatValue];state.liftCm=[p[@"lift_cm"]floatValue];state.lateral=vec(p[@"lateral"]);state.controlState=[p[@"control_state"]intValue];root=ssx::originalRiderRootPresentation(root,local.at(22).position,vec(fixture[@"scale"]),state,&secondaryRoot);}
    auto world=ssx::originalAnimationWorldPose(rig.bones,local,root,vec(fixture[@"scale"]),{root,secondaryRoot});
    if(NSDictionary*c=fixture[@"contact"]){ssx::RiderPoseContact p;p.boardDirection=vec(c[@"board_direction"]);p.normal=vec(c[@"normal"]);p.boardAlignment=[c[@"board_alignment"]floatValue];p.boardLiftCm=[c[@"board_lift_cm"]floatValue];p.legWeight=[c[@"leg_weight"]floatValue];for(unsigned i=0;i<2;++i){NSDictionary*l=c[@"legs"][i];auto&leg=p.legs[i];leg.thigh=[l[@"bones"][0]intValue];leg.shin=[l[@"bones"][1]intValue];leg.foot=[l[@"bones"][2]intValue];NSArray*q=l[@"rotation"];leg.boardLocalFoot={vec(l[@"position"]),{[q[0]floatValue],[q[1]floatValue],[q[2]floatValue],[q[3]floatValue]}};}ssx::originalRiderPoseContact(world,local,vec(fixture[@"scale"]),p);}
    NSMutableArray* rows=[NSMutableArray array];unsigned localExact=0,worldExact=0,worldRotationExact=0;float maxLocal=0,maxWorld=0;
    for(NSUInteger i=0;i<local.size();++i){NSDictionary*expected=fixture[@"bones"][i];NSMutableArray*lp=[NSMutableArray array],*lq=[NSMutableArray array],*wp=[NSMutableArray array],*wq=[NSMutableArray array];bool le=true,we=true,wqe=true;float pe=0,qe=0;
        for(unsigned k=0;k<3;++k){float e=expected[@"local_position_bits"]?std::bit_cast<float>([expected[@"local_position_bits"][k]unsignedIntValue]):[expected[@"local_position"][k]floatValue],w=expected[@"world_position_bits"]?std::bit_cast<float>([expected[@"world_position_bits"][k]unsignedIntValue]):[expected[@"world_position"][k]floatValue];le&=!memcmp(&e,&local[i].position[k],4);we&=!memcmp(&w,&world[i].position[k],4);pe=std::max(pe,std::abs(w-world[i].position[k]));[lp addObject:@(local[i].position[k])];[wp addObject:@(world[i].position[k])];}
        for(unsigned k=0;k<4;++k){float e=expected[@"local_rotation_bits"]?std::bit_cast<float>([expected[@"local_rotation_bits"][k]unsignedIntValue]):[expected[@"local_rotation"][k]floatValue];le&=!memcmp(&e,&local[i].rotation[k],4);qe=std::max(qe,std::abs(e-local[i].rotation[k]));float w=expected[@"world_rotation_bits"]?std::bit_cast<float>([expected[@"world_rotation_bits"][k]unsignedIntValue]):[expected[@"world_rotation"][k]floatValue];wqe&=!memcmp(&w,&world[i].rotation[k],4);[lq addObject:@(local[i].rotation[k])];[wq addObject:@(world[i].rotation[k])];}
        maxLocal=std::max(maxLocal,qe);maxWorld=std::max(maxWorld,pe);localExact+=le;worldExact+=we;worldRotationExact+=wqe;[rows addObject:@{@"index":@(i),@"local_exact":@(le),@"world_position_exact":@(we),@"world_rotation_exact":@(wqe),@"position_error_cm":@(pe),@"local_rotation_error":@(qe),@"local_position":lp,@"local_rotation":lq,@"world_position":wp,@"world_rotation":wq}];}
    NSDictionary*out=@{@"local_exact_bones":@(localExact),@"world_position_exact_bones":@(worldExact),@"world_rotation_exact_bones":@(worldRotationExact),@"max_local_rotation_error":@(maxLocal),@"max_world_position_error_cm":@(maxWorld),@"bones":rows};NSData*encoded=[NSJSONSerialization dataWithJSONObject:out options:NSJSONWritingPrettyPrinted error:nil];fwrite(encoded.bytes,1,encoded.length,stdout);puts("");
}catch(const std::exception&e){fprintf(stderr,"%s\n",e.what());return 1;}}}
