#include "ps2_runtime_macros.h"
#include "../engine/npc_air.hpp"
#include "../engine/original_random.hpp"
#include <fstream>
#include <cfenv>
#include <cstdio>
#include <bit>
#include <random>
#include "npc_provider_registry.inc"
extern const uint32_t g_ps2RecompiledFunctionTableBase=0x100000,g_ps2RecompiledFunctionTableEnd=0x420000,g_ps2RecompiledFunctionTableSlotCount=0xc8000;
PS2Runtime::RecompiledFunction g_ps2RecompiledFunctionTable[0xc8000]={};
int main(int argc,char**argv){
 setbuf(stdout,nullptr);PS2Runtime rt;registerProviderOriginal(rt);std::ifstream file(argv[1],std::ios::binary);std::vector<uint8_t> m((std::istreambuf_iterator<char>(file)),{});if(m.size()!=32*1024*1024)return 2;
 auto u=[&](unsigned at){uint32_t v;std::memcpy(&v,m.data()+at,4);return v;};auto f=[&](unsigned at){return std::bit_cast<float>(u(at));};auto w=[&](unsigned at,auto v){std::memcpy(m.data()+at,&v,sizeof(v));};
 auto context=[](uint32_t pc,uint32_t a0,uint32_t a1=0,uint32_t a2=0,uint32_t a3=0){R5900Context c{};c.pc=pc;c.vu0_vf[0]=_mm_set_ps(1,0,0,0);SET_GPR_U32(&c,4,a0);SET_GPR_U32(&c,5,a1);SET_GPR_U32(&c,6,a2);SET_GPR_U32(&c,7,a3);SET_GPR_U32(&c,28,0x4a30f0);SET_GPR_U32(&c,29,0x10000);SET_GPR_U32(&c,31,0x12345678);return c;};
 auto run=[&](R5900Context& c){for(unsigned k=0;k<128;++k){auto fn=rt.lookupFunction(c.pc);if(!fn)throw std::runtime_error("Missing original NPC air function "+std::to_string(c.pc));fn(m.data(),&c,&rt);if(c.pc==0x12345678)return;}throw std::runtime_error("NPC air continuation limit");};
 unsigned game=u(u(u(0x4a30f0-0x848)+0x84)+0xc);std::array<unsigned,6> actors{};for(unsigned s=0;s<6;++s)actors[s]=u(game+0x28+s*4);
 std::ifstream profiles(argv[2],std::ios::binary);std::array<ssx::OriginalNpcGrabCatalog,5> catalogs;for(auto& g:catalogs){profiles.read((char*)&g.grabStat,4);profiles.read((char*)&g.eventId,4);for(auto* group:{&g.normal,&g.tweak,&g.uber[0],&g.uber[1]})for(auto&e:*group){profiles.read((char*)&e.semantic,4);profiles.read((char*)&e.marker1,4);profiles.read((char*)&e.marker2,4);}}
 std::fesetround(FE_TOWARDZERO);
 for(unsigned slot=1;slot<6;++slot){unsigned actor=actors[slot];auto&g=catalogs[slot-1];for(unsigned group=0;group<4;++group)for(unsigned index=0;index<15;++index){auto c=context(group==0?0x1500d8:group==1?0x150138:0x150198,0,slot,index,group==3);run(c);auto*cp=&c;auto e=group==0?g.normal[index]:group==1?g.tweak[index]:g.uber[group-2][index];if(int(GPR_U32(cp,2))!=e.semantic){printf("NPC grab mapping mismatch slot%u group%u index%u expected%u actual%d\n",slot,group,index,GPR_U32(cp,2),e.semantic);return 3;}if(e.semantic==438)continue;
 for(unsigned marker=1;marker<3;++marker){c=context(0x312820,u(actor+0x784),e.semantic,marker);run(c);float actual=marker==1?e.marker1:e.marker2;if(std::bit_cast<uint32_t>(actual)!=std::bit_cast<uint32_t>(c.f[0])){printf("NPC marker mismatch slot%u semantic%d marker%u %.9g/%.9g\n",slot,e.semantic,marker,c.f[0],actual);return 4;}}}}
 puts("All5 NPC normal/tweak/uber mappings andauthoredmarker timings match original150xxx/312820 exactly");
 std::mt19937 rng(0x10b250);std::uniform_real_distribution<float> val(-10,10);unsigned grabs=0;
 for(unsigned k=0;k<10000;++k){unsigned slot=1+k%5,actor=actors[slot],owner=u(actor+0x77c),angular=owner+0x230;ssx::OriginalNpcAirContext input;input.grabs=&catalogs[slot-1];input.trajectoryStatus=k%5;input.predictedTime=val(rng)+10;input.elapsed=val(rng);input.boostModifier=k%3?0.f:1.f;input.superTime=k%3?0.f:10.f;input.boostTierCounter=k%7;input.uberEnabled=k%2;
 auto stat=context(0x1495a8,0,slot,u(actor+0xb34));run(stat);input.trickStat=stat.f[0];
 auto&a=input.angular;a.targetFlip=val(rng);a.targetSpin=val(rng);a.progressFlip=val(rng);a.progressSpin=val(rng);a.maxSpin=1+std::abs(val(rng));a.maxFlip=1+std::abs(val(rng));
 w(angular+0x10,a.targetFlip);w(angular+0x14,a.targetSpin);w(angular+0x18,a.progressFlip);w(angular+0x1c,a.progressSpin);w(angular+0x38,a.maxSpin);w(angular+0x3c,a.maxFlip);w(angular+0x58,actor);w(actor+0x2ec,input.boostModifier);w(actor+0x2f0,input.superTime);w(actor+0x2f4,input.boostTierCounter);w(actor+0xb2c,uint32_t(input.uberEnabled));
 for(unsigned flip=0;flip<2;++flip){auto c=context(flip?0x135db0:0x135cb0,angular,0x50000,0x50004);run(c);auto times=ssx::originalNpcRotationTimes(a,flip,input.trickStat,input.boostModifier>0);for(unsigned n=0;n<2;++n)if(std::bit_cast<uint32_t>(times[n])!=u(0x50000+n*4)){printf("NPC rotationtimes mismatch%u/%u/%u %.9g/%.9g\n",k,flip,n,f(0x50000+n*4),times[n]);return 5;}}
 ssx::OriginalNpcDrivingState state;state.parameterDFC=float(k%130)/100.f;state.longFlightTicks484=k%33;auto&t=state.trick;t.indexE0C=k%3?-1:int(k%15);t.enabledE10=k%2;t.decisionE14=k%3==0;t.phaseE18=k%7==0;t.fieldE20=k%4==0;t.fieldE24=k%5==0;t.fieldE28=k%6==0;t.spinE38=float(int(k%3)-1);t.flipE3C=float(int(k%4)-1);t.releaseE2C=val(rng);t.startE30=val(rng);t.remainingE34=val(rng);for(auto*counts:{&t.normalCounts,&t.uberCounts,&t.tweakCounts})for(auto&count:*counts)count=rng()%20;
 auto writeState=[&](){w(owner+0xdfc,state.parameterDFC);w(actor+0x484,state.longFlightTicks484);w(owner+0xe0c,t.indexE0C);w(owner+0xe10,t.enabledE10);w(owner+0xe14,t.decisionE14);w(owner+0xe18,t.phaseE18);w(owner+0xe20,t.fieldE20);w(owner+0xe24,t.fieldE24);w(owner+0xe28,t.fieldE28);w(owner+0xe2c,t.releaseE2C);w(owner+0xe30,t.startE30);w(owner+0xe34,t.remainingE34);w(owner+0xe38,t.spinE38);w(owner+0xe3c,t.flipE3C);for(unsigned n=0;n<15;++n){w(owner+0xe7c+n*4,t.normalCounts[n]);w(owner+0xeb8+n*4,t.uberCounts[n]);w(owner+0xef4+n*4,t.tweakCounts[n]);}};
 auto checkState=[&](){bool exact=true;auto eq=[&](unsigned at,auto v){if(u(at)!=std::bit_cast<uint32_t>(v)){printf("field%x original%08x native%08x\n",at-owner,u(at),std::bit_cast<uint32_t>(v));return false;}return true;};exact &=eq(actor+0x484,state.longFlightTicks484)&&eq(owner+0xe0c,t.indexE0C)&&eq(owner+0xe10,t.enabledE10)&&eq(owner+0xe14,t.decisionE14)&&eq(owner+0xe18,t.phaseE18)&&eq(owner+0xe20,t.fieldE20)&&eq(owner+0xe24,t.fieldE24)&&eq(owner+0xe28,t.fieldE28)&&eq(owner+0xe2c,t.releaseE2C)&&eq(owner+0xe30,t.startE30)&&eq(owner+0xe34,t.remainingE34)&&eq(owner+0xe38,t.spinE38)&&eq(owner+0xe3c,t.flipE3C);for(unsigned n=0;n<15;++n)exact &=eq(owner+0xe7c+n*4,t.normalCounts[n])&&eq(owner+0xeb8+n*4,t.uberCounts[n])&&eq(owner+0xef4+n*4,t.tweakCounts[n]);return exact;};
 auto randomState=[&](){ssx::OriginalRandomState r;for(unsigned n=0;n<6;++n)r.words[n]=u(0x4ff030+n*4);return r;};auto checkRandom=[&](const auto&r){for(unsigned n=0;n<6;++n)if(u(0x4ff030+n*4)!=r.words[n])return false;return true;};
 writeState();auto random=randomState();float remaining=float(k%150)/10.f;auto c=context(0x10cad8,owner);c.f[12]=remaining;run(c);auto*cp=&c;int actual=ssx::originalNpcChooseGrab(t,remaining,state.parameterDFC,input,[&](){return random.next();});grabs+=actual>=0;if(GPR_S32(cp,2)!=actual||!checkState()||!checkRandom(random)){printf("NPC grab chooser mismatch%u expected%d actual%d\n",k,GPR_S32(cp,2),actual);return 6;}
 writeState();random=randomState();c=context(0x10b0e8,owner);c.f[12]=remaining;run(c);ssx::originalNpcStopRotations(t,remaining,input);if(!checkState()||!checkRandom(random)){printf("NPC rotationstop mismatch%u\n",k);return 7;}
 writeState();unsigned semantic=k%2?5:288;input.mainAnimationClass=int(u(0x446990+semantic*28));w(u(actor+0x784)+8,semantic);unsigned trajectory=u(actor+0x788);w(trajectory+0xac,input.trajectoryStatus);w(trajectory+0x98,input.predictedTime);w(trajectory+0xa0,input.elapsed);std::array<uint32_t,2> words{rng(),rng()};w(0x50000,words);random=randomState();c=context(0x10b250,owner,0x50000);run(c);auto output=ssx::originalNpcAirCommand(words,state,input,[&](){return random.next();});if(output[0]!=u(0x50000)||output[1]!=u(0x50004)||!checkState()||!checkRandom(random)){printf("NPC aircommand mismatch%u expected%08x %08x actual%08x %08x\n",k,u(0x50000),u(0x50004),output[0],output[1]);return 8;}
 ssx::OriginalNpcDrivingContext driving;driving.position={f(actor+0x110),f(actor+0x114),f(actor+0x118)};driving.velocity={f(actor+0x1e0),f(actor+0x1e4),f(actor+0x1e8)};driving.boardUp={f(actor+0x1c0),f(actor+0x1c4),f(actor+0x1c8)};driving.route.closestPoint={f(actor+0x490),f(actor+0x494),f(actor+0x498)};driving.route.previousLookaheadPoint={f(actor+0x4b0),f(actor+0x4b4),f(actor+0x4b8)};
 writeState();w(0x50000,words);random=randomState();c=context(0x10b590,owner,0x50000);run(c);output=ssx::originalNpcPassiveAirCommand(words,state,driving,input,[&](){return random.next();});if(output[0]!=u(0x50000)||output[1]!=u(0x50004)||!checkState()||!checkRandom(random)){printf("NPC passiveair mismatch%u\n",k);return 9;}

 writeState();w(0x50000,words);int32_t tick=k%2?int32_t(k%500):int32_t(k%500)*20;w(game+8,tick);w(actor+0x86c,slot);w(owner+0xdf0,state.desiredSpeedDF0);random=randomState();c=context(0x10b790,owner,0x50000);run(c);output=ssx::originalNpcStartCommand(words,state,tick,slot,[&](){return random.next();});if(output[0]!=u(0x50000)||output[1]!=u(0x50004)||u(owner+0xdf0)!=std::bit_cast<uint32_t>(state.desiredSpeedDF0)||!checkRandom(random)){printf("NPC startcommand mismatch%u words%08x/%08x DF0%.9g/%.9g\n",k,u(0x50000),output[0],f(owner+0xdf0),state.desiredSpeedDF0);return 10;}

 }
 printf("10000 original NPC rotation times,rotationstop,complete grabchooser(%u selections),air4/5+start6 producers match state/commands/sharedRNG exactly\n",grabs);
}
