#!/usr/bin/env python3
"""Big Challenge missions of the Peak 1 location stages (docs/peak-mountain.md "Big Challenges").

Every location stage (SSB kind 16 record of the location's own track in its last chunk, tools/export_stage_scripts.py)
carries a WScript mission table: stage +0x20 count / +0x24 offset of 0x54-byte mission records, whose steps (tasks) are
0x38-byte records (+0x30 count / +0x34 offset, the mission's +8 points into them). 308C60 builds one WScriptMission
(vtable 0x489A30, 307128 over the WScriptProcess base 307598) per record in free ride:
  mission +0 id (challenge id of table 0x43EE10), +4 step count, +8 step offset, +0xC..+0x14 three process callbacks
  (start / tick / stop -> object +0x28..+0x30), +0x18..+0x3C ten mission event callbacks (+0x34..+0x58), +0x40..+0x4C
  four mission callbacks (+0x68 .. +0x74: +0x6C complete, +0x70 fail, +0x74 status/visual), +0x50 misc (object +0x60,
  2 = Big Challenge).
  step +0 id, +4 start, +8 tick, +0xC end, +0x10..+0x34 ten event callbacks (event kinds 0..9).
Callback words are `program << 8 | track` (0xFFFFFFFF none), resolved at run time against the PEAK1 stage tables.

Also the Big Challenge table 0x43EE10 (88 x 0x24: id, title / objective / description LOC hashes, course, cash, flags,
next, misc).

Output (git-ignored, extracted data):
  web/generated/peak_mission_seed.hpp        namespace browser_missions_peak1 {missions, steps, challenges}
  web/public/assets/BIGCHAL/big-challenges.json  the 88 table rows for the browser UI / career save
SPDX-License-Identifier: GPL-3.0-only
"""
import json, struct, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))
from export_stage_scripts import stage_records  # noqa: E402
from locations import elf_read  # noqa: E402

PEAK1_TRACKS = (1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 33)   # browser_stage_peak1 stages (tools/export_peak_stage.py)
# Peak 3 (docs/peak3.md): the browser_stage_peak3 stages (tools/export_peak_stage.py --peak 3); the core builds a track's
# missions only when that track's stage is in the loaded world (web/mission_gameplay.inc), so the tables can share one seed.
PEAK3_TRACKS = (36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 48)
# Peak 2 (docs/peak2.md): the browser_stage_peak2 stages without DRA4_A (33, in PEAK1_TRACKS) and ERA5_C (46, in PEAK3_TRACKS).
PEAK2_TRACKS = (18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 35)
TABLE, ROWS, STRIDE = 0x43EE10, 88, 0x24
NONE = 0xFFFFFFFF


def missions_of(stage, track):
    u = lambda p: struct.unpack_from('<I', stage, p)[0]
    count, table = u(0x20), u(0x24)
    step_count, step_table = u(0x30), u(0x34)
    out = []
    for i in range(count):
        w = struct.unpack_from('<21I', stage, table + 0x54 * i)
        steps = []
        for k in range(w[1]):
            s = struct.unpack_from('<14I', stage, w[2] + 0x38 * k)
            assert step_table <= w[2] + 0x38 * k < step_table + 0x38 * step_count
            steps.append((s[0], list(s[1:])))
        for ref in list(w[3:20]) + [x for _, sl in steps for x in sl]:
            assert ref == NONE or ref & 255 == track, (track, hex(ref))
        out.append(dict(id=w[0], steps=steps, a=list(w[3:6]), b=list(w[6:16]), c=list(w[16:20]), misc=w[20]))
    return out


def challenge_rows():
    rows = []
    for i in range(ROWS):
        w = struct.unpack('<9I', elf_read(TABLE + STRIDE * i, STRIDE))
        rows.append(dict(index=i, id=w[0], title=w[1], objective=w[2], description=w[3], course=struct.unpack('<i', struct.pack('<I', w[4]))[0],
                         cash=w[5], flags=w[6], next=w[7], misc=w[8]))
    return rows


def main():
    stages, locs = stage_records()
    missions, steps = [], []
    for track in PEAK1_TRACKS + PEAK2_TRACKS + PEAK3_TRACKS:
        for m in missions_of(stages[track], track):
            first = len(steps)
            steps += m['steps']
            missions.append((track, m['id'], first, len(m['steps']), m['a'], m['b'], m['c'], m['misc']))
    rows = challenge_rows()
    ids = {r['id'] for r in rows}
    assert all(m[1] in ids for m in missions), 'mission without a challenge row'
    h = lambda v: f'0x{v:08x}u'
    arr = lambda xs: '{{' + ','.join(h(x) for x in xs) + '}}'
    lines = ['// Generated by tools/export_peak_missions.py: Peak 1 WScript missions and the Big Challenge table (docs/peak-mountain.md).',
             '#pragma once', '#include <array>', '#include <cstdint>', 'namespace browser_missions_peak1 {',
             'struct Mission{uint32_t track,id,firstStep,stepCount;std::array<uint32_t,3> a;std::array<uint32_t,10> b;std::array<uint32_t,4> c;uint32_t misc;};',
             'struct Step{uint32_t id;std::array<uint32_t,13> slots;};',
             'struct Challenge{uint32_t id,title,objective,description;int32_t course;uint32_t cash,flags,next,misc;};',
             f'inline constexpr std::array<Mission,{len(missions)}> missions={{{{']
    lines.append(',\n'.join(f'{{{t}u,{h(i)},{f}u,{n}u,{arr(a)},{arr(b)},{arr(c)},{misc}u}}' for t, i, f, n, a, b, c, misc in missions))
    lines.append('}};')
    lines.append(f'inline constexpr std::array<Step,{len(steps)}> steps={{{{')
    lines.append(',\n'.join(f'{{{h(i)},{arr(sl)}}}' for i, sl in steps))
    lines.append('}};')
    lines.append(f'inline constexpr std::array<Challenge,{ROWS}> challenges={{{{')
    lines.append(',\n'.join(f"{{{h(r['id'])},{h(r['title'])},{h(r['objective'])},{h(r['description'])},{r['course']},{r['cash']}u,{h(r['flags'])},{h(r['next'])},{h(r['misc'])}}}" for r in rows))
    lines.append('}};', )
    lines.append('}')
    out = ROOT / 'web/generated/peak_mission_seed.hpp'
    out.parent.mkdir(parents=True, exist_ok=True)
    text = '\n'.join(lines) + '\n'
    if not out.exists() or out.read_text() != text: out.write_text(text)
    js = ROOT / 'web/public/assets/BIGCHAL/big-challenges.json'
    js.parent.mkdir(parents=True, exist_ok=True)
    js.write_text(json.dumps(dict(source='SLUS_207.72 0x43EE10 (tools/export_peak_missions.py)',
                                  missions={f'{m[1]:08x}': dict(track=m[0], steps=m[3]) for m in missions}, challenges=rows), indent=1) + '\n')
    print(f'{len(missions)} missions, {len(steps)} steps, {ROWS} challenge rows -> {out.relative_to(ROOT)}, {js.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
