#!/usr/bin/env python3
"""Stage scripts of every streamed Peak 1 location for the browser core (docs/peak-mountain.md).

Same tables as tools/export_stage_scripts.py (docs/stage-scripts.md), for the free-ride / peak-run world: one stage per
Peak 1 location (web/public/assets/PEAK1/peak.json, tools/export_peak_world.py), handler rows from each location's own
world_collision.json. The streaming triggers live here: every connector has a Load and an Unload trigger volume
(mdl_<LOC>_Load_0 / _Unload_0, collision node flag 2) whose slot-2 programs call stage builtin 68 (0x302210).
Writes web/generated/peak_stage_seed.hpp, namespace browser_stage_peak1 (web/stage_script_gameplay.inc selects it for
the world location "PEAK1"). No countdown entity audit applies to free ride: every handler instance starts without an
entity (30A060 runs its programs directly).
SPDX-License-Identifier: GPL-3.0-only
"""
import argparse, json, struct, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))
from export_stage_scripts import stage_records, parse_stage  # noqa: E402
from locations import elf_read  # noqa: E402

WEB = ROOT / 'web/public/assets/PEAK1'


def main():
    global WEB
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--peak', type=int, default=1, choices=[1, 2, 3], help='PEAK<N> (docs/peak3.md); 1 = peak_stage_seed.hpp / browser_stage_peak1')
    p.add_argument('--mountain', action='store_true', help='the whole-mountain world MOUNTAIN (tools/export_mountain_world.py): every location of the three peaks, '
                   'web/generated/mountain_stage_seed.hpp / browser_stage_mountain, the collectible award by the current course\'s peak')
    args = p.parse_args(); peak = 0 if args.mountain else args.peak
    WEB = ROOT / ('web/public/assets/MOUNTAIN' if args.mountain else f'web/public/assets/PEAK{peak}')
    stages, locs = stage_records()
    manifest = json.loads((WEB / 'peak.json').read_text())
    stage_rows, program_rows, words, globals_out, handlers = [], [], [], [], []
    for entry in sorted(manifest['locations'], key=lambda l: l['track']):
        track, code = entry['track'], entry['code']
        assert locs[track]['name'] == code
        world = json.loads((ROOT / 'web/public' / entry['root'].lstrip('/') / 'world_collision.json').read_text() if args.mountain else (WEB / code / 'world_collision.json').read_text())
        programs, globals_, rows = parse_stage(stages[track])
        first_program, first_global = len(program_rows), len(globals_out)
        for body in programs:
            program_rows.append((len(words), len(body))); words += body
        for w in globals_:
            assert w == 0xFFFFFFFF or (w & 255) == track
            globals_out.append(-1 if w == 0xFFFFFFFF else w >> 8)
        stage_rows.append((track, first_program, len(programs), first_global, len(globals_)))
        for inst in world['instances']:
            if inst['track'] != track:
                continue
            r08 = world['bindings'][str(track)]['descriptors'][inst['collision_descriptor']]['resource08']
            if r08 == 0xFFFFFFFF:
                continue
            assert r08 & 255 == track and (r08 >> 8) < len(rows), (code, inst['name'], hex(r08))
            slots = []
            for w in rows[r08 >> 8]:
                assert w == 0xFFFFFFFF or (w & 255) == track
                slots.append(-1 if w == 0xFFFFFFFF else w >> 8)
            if any(s >= 0 for s in slots):
                handlers.append(((inst['rid'] << 8) | track, slots))
    handlers.sort()
    assert len({r for r, _ in handlers}) == len(handlers)
    namespace = 'browser_stage_mountain' if args.mountain else f'browser_stage_peak{peak}'
    out = [f'// Generated by tools/export_peak_stage.py: {"the whole mountain" if args.mountain else f"Peak {peak}"} location stages (docs/peak-mountain.md, docs/peak3.md).', '#pragma once',
           '#include <array>', '#include <cstdint>', f'namespace {namespace} {{',
           f'inline constexpr std::array<BrowserStageInfo,{len(stage_rows)}> stages={{{{' + ','.join('{' + ','.join(f'{x}u' for x in s) + '}' for s in stage_rows) + '}};',
           f'inline constexpr std::array<BrowserStageProgram,{len(program_rows)}> programs={{{{' + ','.join(f'{{{a}u,{b}u}}' for a, b in program_rows) + '}};',
           f'inline constexpr std::array<uint32_t,{len(words)}> words={{{{' + ','.join(f'0x{w:x}u' for w in words) + '}};',
           f'inline constexpr std::array<int16_t,{len(globals_out)}> globals={{{{' + ','.join(str(g) for g in globals_out) + '}};',
           f'inline constexpr std::array<BrowserStageHandler,{len(handlers)}> handlers={{{{' + ','.join(f'{{{r}u,{{{{{",".join(str(s) for s in slots)}}}}}}}' for r, slots in handlers) + '}};',
           # 30B9A0 award 151178(course peak) = 500 / 1000 / 2000 on Peak 1 / 2 / 3 (every course row +0x54 of the peak)
           # the whole mountain: -1 = by the current course's peak (144C98 reads 0x535C08's course table +0x54; web/stage_script_gameplay.inc)
           f'inline constexpr int32_t collectible_award={-1 if args.mountain else [500, 1000, 2000][peak - 1]};',
           'inline constexpr std::array<std::array<uint32_t,2>,0> entities={};', '}']
    assert args.mountain or all(struct.unpack('<i', elf_read(0x43D950 + 0x64 * c['course'] + 0x54, 4))[0] == peak - 1 for c in manifest['residency'])
    target = ROOT / ('web/generated/mountain_stage_seed.hpp' if args.mountain else 'web/generated/peak_stage_seed.hpp' if peak == 1 else f'web/generated/peak{peak}_stage_seed.hpp')
    target.write_text('\n'.join(out) + '\n')
    print('wrote', target.relative_to(ROOT), len(stage_rows), 'stages', len(program_rows), 'programs', len(words), 'words', len(handlers), 'handlers')


if __name__ == '__main__':
    main()
