#!/usr/bin/env python3
"""The CTM plane drop's rider orientation and camera state (web/plane-drop.js) from the PS2 savestate of its first race tick.

    python3 tools/export_plane_drop.py [--state local/ps2-capture/menus/fr/ctmstart.f02700.p2s] [--out web/plane-drop.js]

The new career's first ride drops the rider from the plane over Happiness (web/free-ride.js PEAK_STARTS[14] holds its position
and velocity from the same state). There the rider lies head first, its physical forward (+0x1B0) 68 degrees down, and the
DEFAULT_3 camera is 10 ticks into the lock its placement's set-target (0x176FE0: lockView = forward x 250, lock state 1, blend
0.5) started, so it looks steeply down the slope. Exported: the rider quaternion words (+0x120) and the 271 camera words the
core's camera_seed_words takes (the DEFAULT_3 object +0x000..+0x38C and the outer compositor camera's words at
engine/original_camera_words.hpp compositorOffsets)."""
import argparse, json, pathlib, re, struct, sys, zipfile, hashlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))
import ps2_capture as pc
from locations import human_rider
from probe_rider_pose import extract as extract_pose
a = argparse.ArgumentParser(); a.add_argument('--state', default='local/ps2-capture/menus/fr/ctmstart.f02700.p2s'); a.add_argument('--out', default='web/plane-drop.js'); a = a.parse_args()
state = ROOT / a.state; m = zipfile.ZipFile(state).read('eeMemory.bin'); found = pc.discover(m); rider = human_rider(m)
u = lambda at: struct.unpack_from('<I', m, at)[0]
offs = [int(x, 16) for x in re.search(r'compositorOffsets\{([^}]*)\}', (ROOT / 'engine/original_camera_words.hpp').read_text()).group(1).split(',')]
camera = [u(found['camera'] + 4 * i) for i in range(228)] + [u(found['outer'] + k) for k in offs]
quaternion = [u(rider + 0x120 + 4 * i) for i in range(4)]
position = struct.unpack_from('<3f', m, rider + 0x110)
owner = u(rider + 0x77C); st = owner + 0xAD0; ring = u(st + 4)
assert u(st) == rider and u(st + 0x14) == 25, 'air streamer object'
cursor, count = u(st + 8), u(st + 0xC); live = {(cursor - k) % 25 for k in range(count + 1)}   # rows past the count hold stale memory: 0
streamer = [float(cursor), float(count), struct.unpack_from('<f', m, st + 0x10)[0]] + [struct.unpack_from('<f', m, ring + k * 0x20 + e * 0x10 + 4 * i)[0] if k in live else 0.0 for k in range(25) for e in range(2) for i in range(3)]
pose = extract_pose(state, rider, rig_path=ROOT / 'web/public/assets/RIDER_ZOE/rider.json')
animation = json.dumps(dict(layers=pose['layers'], current_semantics=pose['current_semantics']), separators=(',', ':'))
hexs = lambda ws: ','.join(f'0x{w:08x}' for w in ws)
fbits = lambda fs: [struct.unpack('<I', struct.pack('<f', v))[0] for v in fs]
text = f"""// The CTM plane drop (web/free-ride.js PEAK_STARTS[14]) as the PS2 has it on its first race tick: generated by
// tools/export_plane_drop.py from {a.state} (sha256 {hashlib.sha256(state.read_bytes()).hexdigest()[:16]}), rider {hex(rider)}
// at ({position[0]:.1f}, {position[1]:.1f}, {position[2]:.1f}).
// quaternion: rider +0x120 (the rider lies head first, its physical forward +0x1B0 68 degrees down). camera: the 271 words of
// core camera_seed_words (DEFAULT_3 {hex(found['camera'])} +0x000..+0x38C, then the outer camera {hex(found['outer'])} at the compositor
// offsets): 10 ticks into the lock the drop's set-target 0x176FE0 started (lockView = forward x 250), so it looks down the slope.
// streamer: the air streamers (RFX {hex(st)}: cursor, count, scroll, then 25 x {{nose, tail}} x (x, y, z) of board - 0.7 x root) for the core's
// rider_fx_streamer_seed: the scroll 0.81 and 4 rows those 10 ticks left (the ribbon samples strm's bright rows from the start).
// animation: the sequences (tools/probe_rider_pose.py layers, current semantics) for the core's drop_air_seed: the air clip 287 10 ticks in.
// Used by web/main.js resetPhysics (pv dropCamera, dropStreamer, dropPose).
const words = (s) => Uint32Array.from(s.split(','), (x) => parseInt(x, 16));
export const PLANE_DROP = Object.freeze({{
  quaternion: words('{hexs(quaternion)}'),
  camera: words('{hexs(camera)}'),
  animation: {json.dumps(animation)},
  streamer: new Float32Array(words('{hexs(fbits(streamer))}').buffer),
}});
"""
(ROOT / a.out).write_text(text); print(a.out, len(camera), 'camera words')
