#!/usr/bin/env python3
"""Snow Jam falling billboard (development export; ARA1 only): stage handler row 211 (mdl_ARA1_bcvolume_1001,
a 1.7 x 2.1 x 3.3 m type-2 trigger box on the first 1.8 m of the billboard's top-edge rail bcrail_1005) slot 2
(selected rider contact, 121818 -> 30A060) runs program 144:
    builtin2(key1 1)                          0x2FC420 -> 0x2FC2C0 mode 1: 0x3506D8 on the trigger (fires once)
    builtin3(fallingbb_1000, key1 0)          LiveComp 0x341AA0, once mode, full model range (1.333 s), 1/60 s per tick
    builtin48(fallingbb_1000, 0x5B08, node 0) RailModifier 0x35B708: spline_ARA1_fallingbbl_1000 follows node 0
    builtin48(fallingbb_1000, 0x5A08, node 0) RailModifier 0x35B708: spline_ARA1_bcrail_1005 follows node 0
fallingbb_1000's model has one node (node 0: all six channels animated) - the billboard (MERQURY) tips over
about its base; its instance keeps the static collision route (flags 0x210023 -> 0x210125: bit 0x20 stays, the
entity only draws), so the collision mesh stays upright while both top-edge rails swing with node 0 (answered
through the modifier layer 0x35C698 like the log teeters). The LiveComp has no primary modifier, so its
vt+0x15C (0x356AB8) forces are no-ops; its vt+0x154 (0x34E698) surface velocity feeds 0x106F78.

Outputs: web/generated/falling_billboard_seed.hpp (namespace-free BrowserRailLiveCompSeed arrays, raw bits),
local/event-activation/falling-billboard.json (report). The browser LiveComp draw already comes from
LIVECOMP/livecomp.json (tools/export_livecomp.py exports fallingbb_1000 with the contact start of program 144).
"""
import hashlib, json, struct, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))
from set_piece_location import Location  # noqa: E402
from export_startfire import decode_program  # noqa: E402
from export_rail_teeters import parse_model  # noqa: E402


def bits(x): return struct.unpack('<I', struct.pack('<f', float(x)))[0]


def arr(values): return '{' + ','.join(f'0x{v & 0xFFFFFFFF:08x}u' for v in values) + '}'


def main():
    elf = (ROOT / 'local/disc/SLUS_207.72').read_bytes()
    u = lambda a: struct.unpack_from('<I', elf, a - 0xFF000)[0]
    jal = lambda t: 0x0C000000 | (t >> 2)
    assert u(0x441F38 + 2 * 4) == 0x2FC420 and u(0x441F38 + 3 * 4) == 0x2FBCB8 and u(0x441F38 + 48 * 4) == 0x2FF1C8
    assert u(0x2FC590) == jal(0x2FC2C0) and u(0x2FC3A4) == jal(0x3506D8)                 # builtin2 mode 1
    assert u(0x490B10 + 0x15C) == 0x356AB8 and u(0x490B10 + 0x154) == 0x34E698 and u(0x490B10 + 0x1AC) == 0x361158
    loc = Location('ARA1'); track = loc.track; world = loc.world
    by_name = {i['name']: i for i in world['instances'] if i['track'] == track}
    trigger, board = by_name['mdl_ARA1_bcvolume_1001'], by_name['mdl_ARA1_fallingbb_1000']
    res = lambda i: (i['rid'] << 8) | track
    d = world['bindings'][str(track)]['descriptors'][trigger['collision_descriptor']]
    row = loc.row(d['resource08'])
    assert d['resource08'] >> 8 == 211 and row[2] == (144 << 8) | 8 and all(w == 0xFFFFFFFF for k, w in enumerate(row) if k != 2), row
    calls = decode_program(loc.programs[144])
    assert [c[0] for c in calls] == [2, 3, 48, 48], calls
    assert calls[0][2] == {1: ('int', 1)}
    assert calls[1][2] == {0: ('resource', res(board)), 1: ('int', 0)}
    rails = []
    for _, _, keys in calls[2:]:
        assert keys[0] == ('resource', res(board)) and keys[2] == ('int', 0)
        rails.append((keys[1][1], 0))
    assert rails == [(0x5B08, 0), (0x5A08, 0)], rails
    words = [res(board), 0, 0, bits(-1), bits(-1), bits(30), bits(0), bits(-1), 0, 0, 0]   # builtin3 block (defaults + key1 0)
    livecomp = json.loads((ROOT / 'web/public/assets/LIVECOMP/livecomp.json').read_text())
    entry = next(x for x in livecomp['instances'] if x['resource'] == res(board))
    assert entry['starts'][0]['words'] == words and entry['starts'][0]['ownerResource'] == res(trigger)
    model = parse_model(loc.models[board['model_resource'] >> 8])
    catalog = {r['packed_id']: r for r in json.loads((ROOT / 'local/assets/native/ARA1/rails.json').read_text())['rails']}
    for packed, _ in rails: assert catalog[packed]['runtime_flags'] == 0x30003
    audit = {r['resource']: r for r in loc.audit['instances']}
    assert audit[res(board)]['runtime_flags'] == 0x210023 and audit[res(trigger)]['runtime_flags'] == 0x200022
    segs, curves, nodes = [], [], []
    for n in model['nodes']:
        tr = n['track']; fc = len(curves)
        if tr:
            for c in tr['curves']: curves.append((len(segs), len(c))); segs.extend(c)
        nodes.append(f'{{{n["parent"]},{arr(n["bind"])},{1 if tr else 0},{arr(tr["base"] if tr else [0] * 6)},0x{(tr["mask"] if tr else 0):x}u,{fc}u,{len(curves) - fc}u}}')
    sha = loc.audit['world_package_sha256']
    text = f'''#pragma once
// Generated by tools/export_falling_billboard.py (bam.ssb chunk 33 program 144 / row 211, ELF-verified).
// Snow Jam falling billboard: bcvolume_1001 contact -> LiveComp (once, 1.333 s) on fallingbb_1000 + RailModifiers
// binding 0x5B08 / 0x5A08 to its node 0. web/falling_billboard.inc (engine/livecomp_animation.hpp, rail_modifier.hpp).
#include <array>
#include <cstdint>
struct BrowserRailLiveCompSegment {{uint32_t a,b,c,d,t0,t1;}};
struct BrowserRailLiveCompCurve {{uint32_t first,count;}};
struct BrowserRailLiveCompNode {{int32_t parent;std::array<uint32_t,16> bind;uint32_t animated;std::array<uint32_t,6> base;uint32_t mask,firstCurve,curveCount;}};
struct BrowserRailLiveCompRail {{uint32_t packedId;int32_t node;}};
// owner: trigger instance resource (slot 2); words: builtin3 key block; flags: countdown runtime flags of the instance.
struct BrowserRailLiveCompSeed {{const char* name;uint32_t resource,owner,program,flags;std::array<uint32_t,16> matrix;uint32_t scale;
 std::array<uint32_t,3> boundsMin,boundsMax;uint32_t length;std::array<uint32_t,11> words;uint32_t firstNode,nodeCount,firstRail,railCount;}};
inline constexpr const char* browserRailLiveCompWorldHash="{sha}";
inline constexpr std::array<BrowserRailLiveCompSegment,{len(segs)}> browserRailLiveCompSegments={{{{{','.join('{' + ','.join(f'0x{v:08x}u' for v in s) + '}' for s in segs)}}}}};
inline constexpr std::array<BrowserRailLiveCompCurve,{len(curves)}> browserRailLiveCompCurves={{{{{','.join(f'{{{a}u,{b}u}}' for a, b in curves)}}}}};
inline constexpr std::array<BrowserRailLiveCompNode,{len(nodes)}> browserRailLiveCompNodes={{{{{','.join(nodes)}}}}};
inline constexpr std::array<BrowserRailLiveCompRail,{len(rails)}> browserRailLiveCompRails={{{{{','.join(f'{{0x{p:x}u,{n}}}' for p, n in rails)}}}}};
inline constexpr std::array<BrowserRailLiveCompSeed,1> browserRailLiveCompSeeds={{{{{{"{board['name']}",{res(board)}u,{res(trigger)}u,144u,0x{audit[res(board)]['runtime_flags']:x}u,{arr(bits(v) for v in board['matrix'])},0x{bits(board['scale']):08x}u,{arr(bits(v) for v in board['bounds_min_cm'])},{arr(bits(v) for v in board['bounds_max_cm'])},0x{model['length']:08x}u,{arr(words)},0u,{len(nodes)}u,0u,{len(rails)}u}}}}}};
'''
    (ROOT / 'web/generated/falling_billboard_seed.hpp').write_text(text)
    report = dict(source='tools/export_falling_billboard.py', world_package_sha256=sha, trigger=dict(name=trigger['name'], resource=res(trigger), row=211, program=144,
                  bounds_min_cm=trigger['bounds_min_cm'], bounds_max_cm=trigger['bounds_max_cm']),
                  billboard=dict(name=board['name'], resource=res(board), length_s=struct.unpack('<f', struct.pack('<I', model['length']))[0], nodes=len(model['nodes']),
                                 matrix=board['matrix'], scale=board['scale']), rails=[dict(packed_id=p, name=catalog[p]['name'], node=n) for p, n in rails],
                  builtin3_words=words, pad_route='local/ps2-capture/scripts/setpieces-bb-fall.json (fires at tick 1913 on PS2)')
    out = ROOT / 'local/event-activation/falling-billboard.json'; out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=1) + '\n')
    print(f'falling billboard: {board["name"]} ({len(model["nodes"])} node, {report["billboard"]["length_s"]:.3f} s), rails {[hex(p) for p, _ in rails]} -> web/generated/falling_billboard_seed.hpp')


if __name__ == '__main__':
    main()
