import fs from 'node:fs';import createCore from './runtime/core.js';const mode=process.argv[2]||'original';if(!['original','nearest'].includes(mode))throw Error('Unknown native rounding comparison mode');const c=await createCore();const raw=fs.readFileSync('public/assets/ARA1/collision.bin'),v=new Float32Array(raw.buffer,raw.byteOffset,raw.length/4),p=c._malloc(raw.length);c.HEAPF32.set(v,p/4);c._init_world(p,v.length);const terrain=new TextEncoder().encode(fs.readFileSync('public/assets/ARA1/terrain.json','utf8')+'\0'),tp=c._malloc(terrain.length);c.HEAPU8.set(terrain,tp);c._init_terrain(tp);const worldBytes=new TextEncoder().encode(fs.readFileSync('public/assets/ARA1/world_collision.json','utf8')+'\0'),wp=c._malloc(worldBytes.length);c.HEAPU8.set(worldBytes,wp);const hashBytes=new TextEncoder().encode(JSON.parse(fs.readFileSync('public/assets/ARA1/terrain.json')).source_sha256+'\0'),hp=c._malloc(hashBytes.length);c.HEAPU8.set(hashBytes,hp);c._init_world_collision(wp,hp);const start=JSON.parse(fs.readFileSync('public/assets/ARA1/start.json'));c._reset_rider(...start.position,start.heading);const expected=fs.readFileSync(`../local/browser-validation/native-${mode}.csv`,'utf8').trim().split('\n').map(l=>l.split(',').map(value=>Math.fround(Number(value))));let scalarMismatchFrames=0;let maxPositionError=0,maxSpeedError=0,groundMismatches=0,predictionMismatches=0,nativePredictedAirTicks=0,wasmPredictedAirTicks=0;const mismatches=[],positionDivergences=[],wasmRows=[];for(let i=0;i<600;i++){const s=new Float32Array(c.HEAPF32.buffer,c._step_rider(0,+(i>90&&i<150),0,0),16),e=expected[i];scalarMismatchFrames+=Array.from(s).some((value,index)=>value!==e[index]);maxPositionError=Math.max(maxPositionError,Math.hypot(s[0]-e[0],s[1]-e[1],s[2]-e[2]));maxSpeedError=Math.max(maxSpeedError,Math.abs(s[7]-e[7]));groundMismatches+=s[8]!==e[8];const prediction=new Float32Array(c.HEAPF32.buffer,c._prediction_info(),7);predictionMismatches+=prediction[0]!==e[16]||prediction[1]!==e[17]||prediction[6]!==e[18];wasmRows.push([...s,...prediction.slice(0,2),prediction[6]]);
const positionError=Math.hypot(s[0]-e[0],s[1]-e[1],s[2]-e[2]);
if(positionError>.1&&positionDivergences.length<5)positionDivergences.push({tick:i,positionError,nativePosition:e.slice(0,3),wasmPosition:Array.from(s.slice(0,3)),nativeSpeed:e[7],wasmSpeed:s[7]});
if(s[8]!==e[8]||prediction[0]!==e[16]||prediction[1]!==e[17]||prediction[6]!==e[18])mismatches.push({tick:i,nativeGrounded:e[8],wasmGrounded:s[8],nativeLanded:e[11],wasmLanded:s[11],nativeSpeed:e[7],wasmSpeed:s[7],nativePrediction:e.slice(16),wasmPrediction:[prediction[0],prediction[1],prediction[6]]});
nativePredictedAirTicks+=!e[8]&&e[16]===1;wasmPredictedAirTicks+=!s[8]&&prediction[0]===1;}fs.writeFileSync('../local/browser-validation/wasm.csv',wasmRows.map(row=>row.join(',')).join('\n')+'\n');const result={nativeRounding:mode,ticks:600,scalarMismatchFrames,firstPositionDivergences:positionDivergences,stateMismatches:mismatches,maxPositionErrorMeters:maxPositionError,maxSpeedErrorMps:maxSpeedError,groundStateMismatches:groundMismatches,predictionStateMismatches:predictionMismatches,nativePredictedAirTicks,wasmPredictedAirTicks,note:`Scalar no-animation trace; same imported terrain/object world. Native rounding policy: ${mode}; WASM uses scoped software chop in shared arithmetic; remaining direct operations use nearest. This is not full gameplay or original-game/PCSX2 parity.`};console.log(result);fs.writeFileSync(`../local/browser-validation/native-${mode}-vs-wasm.json`,JSON.stringify(result,null,2));

// Nearest mode was an exact baseline before directed-arithmetic integration.
// It is now a diagnostic contrast; only original-policy parity is the target.


if(mode==='original'&&(scalarMismatchFrames||predictionMismatches))throw Error('Original-policy native and WASM scalar trace diverged');
