// three r186 patches for per-draw JS garbage (docs/web-render-performance.md "Per-frame garbage"; Owen approved patching three,
// 2026-09-29). Generated by tools/gen_three_patches.py from the exact three source; applied to node_modules/three/build/three.webgpu.js
// as Vite transforms, in the build (plugins) and in the dev server's dependency pre-bundle (optimizeDeps.rolldownOptions.plugins).
// Each find must occur exactly once, or the build fails (a three upgrade must re-check them). The patched paths run only with
// globalThis.__ssxThreeLean === true (web/main.js from pv threeLean); otherwise three's own code runs.
// 1. RenderObject.getDynamicCacheKey (every draw): cyrb53 over reused argument arrays instead of hash$1( ...params ).
// 2. Bindings._update: the key's attribute / texture ids kept on the bind group; the key string built only for updateBindings.
// 3. Textures.updateTexture: the default options object made after the early return.
// 4. WebGPUTextureUtils.updateSampler: an unchanged sampler state returns its key without building the string.
const PATCHES = [
 {
  "name": "hash scratch",
  "find": "const hash$1 = ( ...params ) => cyrb53( params );",
  "replace": "const hash$1 = ( ...params ) => cyrb53( params );\n\n// ssx three-patches (web/three-patches.js): reused argument arrays for the per-draw hashes (same cyrb53 input)\nconst _ssxHash2 = [ 0, 0 ], _ssxHash3 = [ 0, 0, 0 ];"
 },
 {
  "name": "dynamic cache key",
  "find": "\t\tif ( this.camera.isArrayCamera ) {\n\n\t\t\tcacheKey = hash$1( cacheKey, this.camera.cameras.length );\n\n\t\t}\n\n\t\tif ( this.object.receiveShadow ) {\n\n\t\t\tcacheKey = hash$1( cacheKey, 1 );\n\n\t\t}\n\n\t\tcacheKey = hash$1( cacheKey, this.renderer.contextNode.id, this.renderer.contextNode.version );\n\n\t\treturn cacheKey;",
  "replace": "\t\tif ( globalThis.__ssxThreeLean === true ) { // ssx three-patches: hash$1( ...params ) without the rest array per draw\n\n\t\t\tif ( this.camera.isArrayCamera ) { _ssxHash2[ 0 ] = cacheKey; _ssxHash2[ 1 ] = this.camera.cameras.length; cacheKey = cyrb53( _ssxHash2 ); }\n\t\t\tif ( this.object.receiveShadow ) { _ssxHash2[ 0 ] = cacheKey; _ssxHash2[ 1 ] = 1; cacheKey = cyrb53( _ssxHash2 ); }\n\t\t\t_ssxHash3[ 0 ] = cacheKey; _ssxHash3[ 1 ] = this.renderer.contextNode.id; _ssxHash3[ 2 ] = this.renderer.contextNode.version;\n\t\t\treturn cyrb53( _ssxHash3 );\n\n\t\t}\n\n\t\tif ( this.camera.isArrayCamera ) {\n\n\t\t\tcacheKey = hash$1( cacheKey, this.camera.cameras.length );\n\n\t\t}\n\n\t\tif ( this.object.receiveShadow ) {\n\n\t\t\tcacheKey = hash$1( cacheKey, 1 );\n\n\t\t}\n\n\t\tcacheKey = hash$1( cacheKey, this.renderer.contextNode.id, this.renderer.contextNode.version );\n\n\t\treturn cacheKey;"
 },
 {
  "name": "bindings key ids",
  "find": "\t\tlet cacheBindings = true;\n\t\tlet cacheKey = '';\n\t\tlet version = 0;",
  "replace": "\t\tlet cacheBindings = true;\n\t\tlet cacheKey = '';\n\t\tlet version = 0;\n\t\t// ssx three-patches: the key's ids, kept on the bind group; the string is built only for updateBindings\n\t\tconst ssxLean = globalThis.__ssxThreeLean === true, ssxIds = ssxLean ? ( bindGroup._ssxKeyIds || ( bindGroup._ssxKeyIds = [] ) ) : null;\n\t\tlet ssxCount = 0;"
 },
 {
  "name": "bindings attribute id",
  "find": "\t\t\t\t\tneedsBindingsUpdate = true;\n\n\t\t\t\t}\n\n\t\t\t\tcacheKey += attribute.id + ',';",
  "replace": "\t\t\t\t\tneedsBindingsUpdate = true;\n\n\t\t\t\t}\n\n\t\t\t\tif ( ssxLean ) ssxIds[ ssxCount ++ ] = attribute.id; else cacheKey += attribute.id + ',';"
 },
 {
  "name": "bindings texture id",
  "find": "\t\t\t\t\tcacheKey += texture.id + ',';",
  "replace": "\t\t\t\t\tif ( ssxLean ) ssxIds[ ssxCount ++ ] = texture.id; else cacheKey += texture.id + ',';"
 },
 {
  "name": "bindings key string",
  "find": "\t\tif ( needsBindingsUpdate === true ) {\n\n\t\t\tthis.backend.updateBindings( bindGroup, bindings, cacheBindings ? cacheKey : '', version );",
  "replace": "\t\tif ( needsBindingsUpdate === true ) {\n\n\t\t\tif ( ssxLean && cacheBindings ) for ( let i = 0; i < ssxCount; i ++ ) cacheKey += ssxIds[ i ] + ',';\n\t\t\tthis.backend.updateBindings( bindGroup, bindings, cacheBindings ? cacheKey : '', version );"
 },
 {
  "name": "updateTexture options",
  "find": "\tupdateTexture( texture, options = {} ) {\n\n\t\tconst textureData = this.get( texture );\n\t\tif ( textureData.initialized === true && textureData.version === texture.version ) return;",
  "replace": "\tupdateTexture( texture, options ) {\n\n\t\t// ssx three-patches: the default options object only past the early return\n\t\tif ( options === undefined && globalThis.__ssxThreeLean !== true ) options = {};\n\n\t\tconst textureData = this.get( texture );\n\t\tif ( textureData.initialized === true && textureData.version === texture.version ) return;\n\t\tif ( options === undefined ) options = {};"
 },
 {
  "name": "updateSampler fast path",
  "find": "\tupdateSampler( binding ) {\n\n\t\tconst backend = this.backend;\n\t\tconst texture = binding.texture;\n\t\tconst textureNode = binding.textureNode;\n\n\t\tconst isComparison = texture.isDepthTexture === true && texture.compareFunction !== null && textureNode.isSampleCompare() && backend.hasCompatibility( Compatibility.TEXTURE_COMPARE );",
  "replace": "\tupdateSampler( binding ) {\n\n\t\tconst backend = this.backend;\n\t\tconst texture = binding.texture;\n\t\tconst textureNode = binding.textureNode;\n\n\t\tconst isComparison = texture.isDepthTexture === true && texture.compareFunction !== null && textureNode.isSampleCompare() && backend.hasCompatibility( Compatibility.TEXTURE_COMPARE );\n\t\t// ssx three-patches: the key of an unchanged sampler state, without building the string (the original finds the same cache\n\t\t// entry, whose sampler is already the binding's, and returns that key)\n\t\tconst ssxLean = globalThis.__ssxThreeLean === true;\n\t\tif ( ssxLean ) {\n\n\t\t\tconst d = backend.get( binding ), m = d._ssxSampler;\n\t\t\tif ( m !== undefined && d.sampler !== undefined && d.samplerKey === m.key && m.minFilter === texture.minFilter && m.magFilter === texture.magFilter &&\n\t\t\t\tm.wrapS === texture.wrapS && m.wrapT === texture.wrapT && m.wrapR === texture.wrapR && m.anisotropy === texture.anisotropy &&\n\t\t\t\tm.depth === ( texture.isDepthTexture === true ) && m.comparison === isComparison && m.compareFunction === texture.compareFunction ) {\n\n\t\t\t\tconst cached = this._samplerCache.get( m.key );\n\t\t\t\tif ( cached !== undefined && cached.sampler === d.sampler ) return m.key;\n\n\t\t\t}\n\n\t\t}\n"
 },
 {
  "name": "updateSampler memo",
  "find": "\t\t\tsamplerData.usedTimes ++;\n\n\t\t}\n\n\t\treturn samplerKey;",
  "replace": "\t\t\tsamplerData.usedTimes ++;\n\n\t\t}\n\n\t\tif ( ssxLean ) {\n\n\t\t\tconst d = backend.get( binding ), m = d._ssxSampler || ( d._ssxSampler = {} );\n\t\t\tm.key = d.samplerKey; m.minFilter = texture.minFilter; m.magFilter = texture.magFilter; m.wrapS = texture.wrapS; m.wrapT = texture.wrapT;\n\t\t\tm.wrapR = texture.wrapR; m.anisotropy = texture.anisotropy; m.depth = texture.isDepthTexture === true; m.comparison = isComparison; m.compareFunction = texture.compareFunction;\n\n\t\t}\n\n\t\treturn samplerKey;"
 }
];
export const THREE_PATCH_VERSION = '068f9194248c';
const TARGET = /[\\/]node_modules[\\/]three[\\/]build[\\/]three\.webgpu\.js$/;
export function patchThree(code, id = 'three.webgpu.js') {
  for (const p of PATCHES) {
    const n = code.split(p.find).length - 1;
    if (n !== 1) throw new Error(`three-patches: "${p.name}" matches ${n} times in ${id} (three changed? rerun tools/gen_three_patches.py)`);
    code = code.split(p.find).join(p.replace);
  }
  return code;
}
export default function threePatches() {
  return {
    name: 'ssx-three-patches', version: THREE_PATCH_VERSION, enforce: 'pre',
    transform(code, id) { if (!TARGET.test(id.split('?')[0])) return null; return { code: patchThree(code, id), map: null }; },
  };
}
