"""Collect the PS2 hardware rows behind engine/ps2_fpu.hpp into one C++ header.

usage: extract_console_rows.py ARMSX2_SRC PS2AUTOTESTS_DIR OUT_HEADER

Sources (docs/ps2-float.md "Hardware data"):
  - ARMSX2's console captures (SCPH-90000), in its tests/ctest/core/recompilers: the
    autocases_*.h headers are copied whole; from the *_console_tests.cpp files only the
    row tables and the enums / structs / constants they need are copied.
  - unknownbrackets/ps2autotests tests/cpu/ee_fpu/*.expected (real PS2 output), parsed
    into one flat table.
The header is generated from GPL-3.0 sources (ARMSX2) and stays under local/ (not committed).
"""
import re
import sys
from pathlib import Path


def block_end(text, start):
    depth = 0
    index = text.index('{', start)
    while True:
        char = text[index]
        if char == '{':
            depth += 1
        elif char == '}':
            depth -= 1
            if depth == 0:
                end = text.index(';', index)
                return end + 1
        index += 1


def named_block(text, pattern):
    match = re.search(pattern, text, re.M)
    if not match:
        raise KeyError(pattern)
    return text[match.start():block_end(text, match.start())]


# file -> list of regexes of declarations to copy, in order
CPP_TABLES = {
    'ee_fpu_guarded_addsub_console_tests.cpp': [r'^enum Form\b', r'^struct ConsoleCase\b', r'^constexpr ConsoleCase kConsole\[\]'],
    'ee_fpu_underflow_console_tests.cpp': [r'^enum Form\b', r'^struct ConsoleCase\b', r'^constexpr ConsoleCase kConsole\[\]'],
    'ee_fpu_top_binade_console_tests.cpp': [r'^enum Form\b', r'^struct ConsoleCase\b', r'^constexpr ConsoleCase kConsole\[\]'],
    'ee_fpu_ou_rounding_console_tests.cpp': [r'^enum Form\b', r'^struct ConsoleCase\b', r'^constexpr ConsoleCase kConsole\[\]'],
    'ee_fpu_minmax_console_tests.cpp': [r'^struct ConsoleCase\b', r'^constexpr ConsoleCase kConsole\[\]'],
    'ee_fpu_compare_console_tests.cpp': [r'^enum Cond\b', r'^struct ConsoleCase\b', r'^constexpr ConsoleCase kConsole\[\]'],
    'ee_fpu_rsqrt_sign_console_tests.cpp': [r'^enum RsqOp\b', r'^struct Row\b', r'^constexpr Row kRows\[\]'],
    'ee_fpu_divunit_console_tests.cpp': [r'^struct ConsoleRow\b', r'^constexpr ConsoleRow kRows\[\]'],
}

AUTOCASES = ['autocases_fpuovf.h', 'autocases_vgmask.h', 'autocases_vumadd.h', 'autocases_vusat.h', 'autocases_vuflow.h',
             'autocases_vuzsign.h', 'autocases_vurs.h']

AUTOTEST_FILES = ['arithmetic', 'muldiv', 'sqrt', 'convert', 'compare']


def autotest_constants(shared):
    constants = {}
    for name, value in re.findall(r'(CF_[A-Z0-9_]+)\[\d+\] = \{(0x[0-9A-Fa-f]+)', shared):
        constants[name] = int(value, 16)
    return constants


def autotest_word(token, constants):
    token = token.strip()
    if token in constants:
        return constants[token]
    return int(token.split('/')[0], 16)


def autotest_rows(directory):
    constants = autotest_constants((directory / 'shared.h').read_text())
    rows = []
    for name in AUTOTEST_FILES:
        for line in (directory / f'{name}.expected').read_text().splitlines():
            match = re.match(r'^  ([a-z.]+) (.*): (.*)$', line)
            if not match:
                continue
            op, arguments, result = match.groups()
            acc = None
            accumulate = re.match(r'^\(([^)]*)\) (.*)$', arguments)
            if accumulate:
                acc = autotest_word(accumulate.group(1), constants)
                arguments = accumulate.group(2)
            operands = [autotest_word(part, constants) for part in arguments.split(', ')]
            result_acc = None
            result_match = re.match(r'^(\S+)(?: \((\S+)\))?$', result)
            text = result_match.group(1)
            if result_match.group(2):
                result_acc = autotest_word(result_match.group(2), constants)
            if text in ('true', 'false'):
                value = 1 if text == 'true' else 0
            else:
                value = autotest_word(text, constants)
            rows.append((name, op, operands, acc, value, result_acc))
    return rows


def main():
    source = Path(sys.argv[1]) / 'tests/ctest/core/recompilers'
    autotests = Path(sys.argv[2])
    out = Path(sys.argv[3])
    parts = ['// GENERATED by tools/ps2-float/extract_console_rows.py -- do not edit. GPL-3.0 sources (ARMSX2).', '#pragma once',
             '#include <cstdint>', 'using u8 = uint8_t;', 'using u16 = uint16_t;', 'using u32 = uint32_t;', 'using s32 = int32_t;',
             'using u64 = uint64_t;', '']
    for name in AUTOCASES:
        text = (source / name).read_text()
        text = text.replace('#pragma once', '').replace('#include <common/Pcsx2Types.h>', '')
        text = text.replace('#include "common/Pcsx2Types.h"', '')
        parts.append(f'// ---- {name}')
        parts.append(text)
    for name, patterns in CPP_TABLES.items():
        text = (source / name).read_text()
        namespace = 'f_' + name.replace('.cpp', '')
        parts.append(f'// ---- {name}')
        parts.append(f'namespace {namespace} {{')
        for flag in re.findall(r'^constexpr u32 (FPUflag[A-Z]+) = [^;]+;', text, re.M):
            pass
        for line in re.findall(r'^constexpr u32 (?:FPUflag|k)[A-Za-z0-9_]+ = [^;]+;', text, re.M):
            parts.append(line)
        for pattern in patterns:
            parts.append(named_block(text, pattern))
        parts.append('}')
    parts.append('// ---- ps2autotests tests/cpu/ee_fpu/*.expected')
    parts.append('struct AutotestRow { const char* file; const char* op; u32 operands[3]; int count; bool hasAcc; u32 acc; u32 result;'
                 ' bool hasResultAcc; u32 resultAcc; };')
    parts.append('inline constexpr AutotestRow kAutotestRows[] = {')
    for file, op, operands, acc, value, result_acc in autotest_rows(autotests):
        padded = operands + [0] * (3 - len(operands))
        words = ', '.join(f'0x{w:08X}u' for w in padded)
        parts.append(f'    {{"{file}", "{op}", {{{words}}}, {len(operands)}, {"true" if acc is not None else "false"}, '
                     f'0x{(acc or 0):08X}u, 0x{value:08X}u, {"true" if result_acc is not None else "false"}, 0x{(result_acc or 0):08X}u}},')
    parts.append('};')
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(parts) + '\n')


if __name__ == '__main__':
    main()
